export const Permissoes = {
  // Ver página de Empresas em Empresas e grupos
  GESTAO_EMPRESA_CONSULTAR: "GESTAO_EMPRESA_CONSULTAR",
  // Ver página de criar/atualizar empresa em Empresas e grupos
  GESTAO_EMPRESA_CADASTRAR: "GESTAO_EMPRESA_CADASTRAR",
  // Ver página de gestão de acessos em Empresas e grupos
  GESTAO_EMPRESA_USUARIO_MASTER_CONSULTAR: "GESTAO_EMPRESA_USUARIO_MASTER_CONSULTAR",
  // Ver página de criar perfil dentro de gestão de acessos em Empresas e grupos
  GESTAO_EMPRESA_USUARIO_MASTER_CADASTRAR: "GESTAO_EMPRESA_USUARIO_MASTER_CADASTRAR",
  GESTAO_EMPRESA_USUARIO_CRM_CADASTRAR: "GESTAO_EMPRESA_USUARIO_CRM_CADASTRAR",
  GESTAO_EMPRESA_USUARIO_CONVIDADO_CONSULTAR: "GESTAO_EMPRESA_USUARIO_CONVIDADO_CONSULTAR",
  GESTAO_EMPRESA_USUARIO_CONVIDADO_CADASTRAR: "GESTAO_EMPRESA_USUARIO_CONVIDADO_CADASTRAR",
  GESTAO_EMPRESA_USUARIO_API_CONSULTAR: "GESTAO_EMPRESA_USUARIO_API_CONSULTAR",
  GESTAO_EMPRESA_USUARIO_API_INATIVAR_ATIVAR: "GESTAO_EMPRESA_USUARIO_API_INATIVAR_ATIVAR",
  GESTAO_EMPRESA_USUARIO_API_REDEFINIR_SENHA: "GESTAO_EMPRESA_USUARIO_API_REDEFINIR_SENHA",
  GESTAO_EMPRESA_USUARIO_API_ENVIAR_CREDENCIAIS: "GESTAO_EMPRESA_USUARIO_API_ENVIAR_CREDENCIAIS",

  // Ver página de Grupos Economicos em Empresas e grupos
  GESTAO_EMPRESA_GRUPO_ECONOMICO_CONSULTAR: "GESTAO_EMPRESA_GRUPO_ECONOMICO_CONSULTAR",
  // Ver página de criar/atualizar grupo em Empresas e grupos
  GESTAO_EMPRESA_GRUPO_ECONOMICO_CADASTRAR: "GESTAO_EMPRESA_GRUPO_ECONOMICO_CADASTRAR",

  GESTAO_USUARIO_INTERNO_CONSULTAR: "GESTAO_USUARIO_INTERNO_CONSULTAR",
  GESTAO_USUARIO_INTERNO_CADASTRAR: "GESTAO_USUARIO_INTERNO_CADASTRAR",

  GESTAO_RELATORIOS_GERAR: "GESTAO_RELATORIOS_GERAR",

  //Ver página de Consultar Dudas
  GESTAO_OPERACOES_DUDA_CONSULTAR: "GESTAO_OPERACOES_DUDA_CONSULTAR", 
  GESTAO_OPERACOES_DUDA_PARAMETRIZAR: "GESTAO_OPERACOES_DUDA_PARAMETRIZAR",
  GESTAO_OPERACOES_DUDA_COMPRAR_MANUAL: "GESTAO_OPERACOES_DUDA_COMPRAR_MANUAL",
  GESTAO_OPERACOES_IMAGEM_CONSULTAR: "GESTAO_OPERACOES_IMAGEM_CONSULTAR",
  GESTAO_OPERACOES_ARQUIVOS_RETORNO_LOTE_CONSULTAR: "GESTAO_OPERACOES_ARQUIVOS_RETORNO_LOTE_CONSULTAR",
  
  //Ver página de Monitor de operações e lotes
  GESTAO_OPERACOES_CONTRATO_CONSULTAR: "GESTAO_OPERACOES_CONTRATO_CONSULTAR",
  GESTAO_OPERACOES_CONTRATO_REGISTRAR: "GESTAO_OPERACOES_CONTRATO_REGISTRAR",
  GESTAO_OPERACOES_CONTRATO_REENVIAR: "GESTAO_OPERACOES_CONTRATO_REENVIAR",
  GESTAO_OPERACOES_LOTE_REGISTRAR: "GESTAO_OPERACOES_LOTE_REGISTRAR",
  GESTAO_OPERACOES_DSENVIO_DSRETORNO_CONSULTAR: "GESTAO_OPERACOES_DSENVIO_DSRETORNO_CONSULTAR",

  //Ver página de Consultar Gravame
  GESTAO_OPERACOES_GRAVAME_CONSULTAR: "GESTAO_OPERACOES_GRAVAME_CONSULTAR",

  //Ver página de Conexão Detrans
  GESTAO_OPERACOES_CONEXAO_DETRAN_CONSULTAR: "GESTAO_OPERACOES_CONEXAO_DETRAN_CONSULTAR",

  GESTAO_COMUNICADOS_CONSULTAR: "GESTAO_COMUNICADOS_CONSULTAR",
  GESTAO_COMUNICADOS_CADASTRAR: "GESTAO_COMUNICADOS_CADASTRAR",

  //Ver página de /configuracoes-imagens 
  PARAMETRIZACAO_IMAGENS_REGRA_IMAGEM_CONSULTAR: "PARAMETRIZACAO_IMAGENS_REGRA_IMAGEM_CONSULTAR",
  //Ver página de /configuracoes-imagens/editar-detran & /configuracoes-imagens/registrar-detran
  PARAMETRIZACAO_IMAGENS_REGRA_IMAGEM_PARAMETRIZAR: "PARAMETRIZACAO_IMAGENS_REGRA_IMAGEM_PARAMETRIZAR",

  GESTAO_CENTRAL_AJUDA_CONSULTAR: 'GESTAO_CENTRAL_AJUDA_CONSULTAR',
  GESTAO_CENTRAL_AJUDA_CADASTRAR: 'GESTAO_CENTRAL_AJUDA_CADASTRAR',

  //Ver monitor de faturamento
  GESTAO_FINANCEIRO_MONITOR_FATURAMENTO: 'GESTAO_FINANCEIRO_MONITOR_FATURAMENTO',
  //Aprovar cancelamento de notas
  GESTAO_FINANCEIRO_APROVAR_CANCELAMENTO_NF_ND: 'GESTAO_FINANCEIRO_APROVAR_CANCELAMENTO_NF_ND',

  //Cadastrar preços
  GESTAO_FINANCEIRO_PRECO_CADASTRAR: 'GESTAO_FINANCEIRO_PRECO_CADASTRAR',
  //Ver página de preços
  GESTAO_FINANCEIRO_PRECO_CONSULTAR: 'GESTAO_FINANCEIRO_PRECO_CONSULTAR',
  //Aprovar preços
  GESTAO_FINANCEIRO_APROVACAO_PRECO_TECNOBANK: 'GESTAO_FINANCEIRO_APROVACAO_PRECO_TECNOBANK',

  //Ver página de relatórios financeiro
  GESTAO_FINANCEIRO_RELATORIOS: 'GESTAO_FINANCEIRO_RELATORIOS',
  //Ver página de upload de arquivo detran
  GESTAO_FINANCEIRO_UPLOAD_ARQUIVO_DETRAN: 'GESTAO_FINANCEIRO_UPLOAD_ARQUIVO_DETRAN',
}
