import { Permissoes } from "./permissoes";

export const PermissoesRotas = {
  MONITOR_OPERACOES_LOTES: [
    Permissoes.GESTAO_OPERACOES_CONTRATO_CONSULTAR,
    Permissoes.GESTAO_OPERACOES_CONTRATO_REGISTRAR,
    Permissoes.GESTAO_OPERACOES_CONTRATO_REENVIAR,
    Permissoes.GESTAO_OPERACOES_LOTE_REGISTRAR,
    Permissoes.GESTAO_OPERACOES_DSENVIO_DSRETORNO_CONSULTAR,
  ],

  ACESSOS_USUARIO_INTERNO: ['GESTAO_USUARIO_INTERNO'],
  ACESSOS_USUARIO_INTERNO_CADASTRAR: [Permissoes.GESTAO_USUARIO_INTERNO_CADASTRAR],

  GESTAO_EMPRESAS_GRUPOS: ['GESTAO_EMPRESA'],
  GESTAO_EMPRESAS_CADASTRAR: [Permissoes.GESTAO_EMPRESA_CADASTRAR],

  GESTAO_EMPRESAS_ACESSOS: ['GESTAO_EMPRESA_USUARIO'],
  GESTAO_EMPRESAS_ACESSOS_CADASTRAR: [Permissoes.GESTAO_EMPRESA_USUARIO_CRM_CADASTRAR],

  GESTAO_EMPRESAS_GRUPOS_CADASTRAR: [Permissoes.GESTAO_EMPRESA_GRUPO_ECONOMICO_CADASTRAR],
  GESTAO_EMPRESAS_GRUPOS_CONVIDADO_CADASTRAR: [Permissoes.GESTAO_EMPRESA_USUARIO_CONVIDADO_CADASTRAR],

  GESTAO_OPERACOES_DUDAS: ['GESTAO_OPERACOES_DUDA'],
  GESTAO_OPERACOES_DUDAS_PARAMETRIZAR: [Permissoes.GESTAO_OPERACOES_DUDA_PARAMETRIZAR],
  GESTAO_OPERACOES_DUDAS_COMPRAR: [Permissoes.GESTAO_OPERACOES_DUDA_COMPRAR_MANUAL],

  GESTAO_OPERACOES_CONEXAO_DETRAN: [Permissoes.GESTAO_OPERACOES_CONEXAO_DETRAN_CONSULTAR],

  CONFIGURACOES_ECONTRATO_IMAGENS: ['PARAMETRIZACAO_IMAGENS_REGRA_IMAGEM'],
  CONFIGURACOES_ECONTRATO_IMAGENS_CADASTRAR: [Permissoes.PARAMETRIZACAO_IMAGENS_REGRA_IMAGEM_PARAMETRIZAR],

  NOTIFICACOES: ['GESTAO_COMUNICADOS'],
  NOTIFICACOES_CADASTRAR: [Permissoes.GESTAO_COMUNICADOS_CADASTRAR],

  CENTRAL_AJUDA: ['GESTAO_CENTRAL_AJUDA'],
  CENTRAL_AJUDA_CADASTRAR: [Permissoes.GESTAO_CENTRAL_AJUDA_CADASTRAR],

  GESTAO_OPERACOES_GRAVAME_CONSULTAR: [Permissoes.GESTAO_OPERACOES_GRAVAME_CONSULTAR],

  GESTAO_FATURAMENTO: ['GESTAO_FINANCEIRO'],

  GESTAO_FINANCEIRO_RELATORIOS: [Permissoes.GESTAO_FINANCEIRO_RELATORIOS],

  MONITOR_FATURAMENTO: [Permissoes.GESTAO_FINANCEIRO_MONITOR_FATURAMENTO],

  GESTAO_DETRANS: [
    Permissoes.GESTAO_FINANCEIRO_PRECO_CONSULTAR,
    Permissoes.GESTAO_FINANCEIRO_PRECO_CADASTRAR,
    Permissoes.GESTAO_FINANCEIRO_APROVACAO_PRECO_TECNOBANK],

  UPLOAD_ARQUIVO_DETRAN: [Permissoes.GESTAO_FINANCEIRO_UPLOAD_ARQUIVO_DETRAN],

  GESTAO_FINANCEIRO_APROVACOES: ['GESTAO_FINANCEIRO_APROVA']
};